language: node_js
install: npm ci
cache:
  directories:
  - "$HOME/.npm"
script: npm run pretest && npm run coverage
deploy:
  provider: npm
  skip_cleanup: true
  email: bernardo.sunderhus@gmail.com
  api_key:
    secure: D68+hg/1PUgnyyBxdjIoQb3qAnpiB67EqV3NztYQFfAFUSRwEY8GQzG5wrbL1+sKOdJHBeHtxhQ73vJ5S1n1Hu7E5Oueq7tNFBvknaTX52FiEDoQeSYoENsIV9fSPgAXDlqHDQiEc/NBb8EQWFppaur7QT0Uaa0mdHe6mzg0zMpnuwDAWdEBZVyYq0vk5gi9Gu3Eexyb4Rc3QNio/YfP0/uTie2GJ9vTH0BPwfDtICDmL5E/tIG5XxcUgZlfaM6fgvUK9om09FqT6nBLpLeUkXOTrmtyzhx9Q9xvs+75WkakAsRZzC3X+KHqdhEfonwPK7iwQVMzMBu+0Fk5cBCzHR2ybBUmUO6ciaUIHyORUTpQHTQm7JEcz/1hoY1OdltOzcg1hRZXyOOyEMvsWqBIemic6ceLf0tUj1DWFL7X2BBZbynCGP5MAMU+iRqojQVKmz7eoNuMeoYk6aGfSd03pCBa6MOmdefCuTLFm+4DObwuihtGMSj8SO90xhV1+IKoJil1HITZlJgaVOA3Olj1b5LIy2afqfanLrM3JCd0wMF052bVP4nVxGb5qE2z4Ks5AK6Bl7zC8Ha9X2ZSOt5QahZgZwLNMXDqA5tMys+tdbnatA8Njsvz6/CiFjuxtFlrIFKGEDXX98Njd0lr4iUdIH95U+VuArkrldvjFf32coY=
  on:
    tags: true
    branch: master
    repo: bsunderhus/html-module-loader
