language: node_js
install: npm ci
cache:
  directories:
  - "$HOME/.npm"
script: npm run pretest && npm run coverage
deploy:
  provider: npm
  skip_cleanup: true
  email: bernardo.sunderhus@gmail.com
  api_key:
    secure: h3cfNS1BCXxyt2MVGghTVQV7HbQQ4KXNKB3XPYNyS8W4a7Ug1RlnVwOQoV9Op2HqIXUsAUtyWyxljX/codmY7rLWKHO8tBpVVFnX23RRSFr0Qz9LprfvTN/p35gnMBVKFWWvxI8GznbmfjT6UXfoXF/jKk3lpozwqaHodgR9p8IlHbWk7Axf1AkJRTifxyKpKmGxvYCx/eQcCW6n3hmXF8+xnI6qlK8LUB7eVjyEXsMUzb1krskH/s0M5r4AuIaKRXah56IvY6/n8IAHy0SBKiystK9ID8e2vALoxIXKiusMh235yUh31id8JqI8ZJlgdFtZlGywEN5O35CRH6Q+lwTGkAV8+IS5e5DhHnEwGzqP94l6rnsEHavthP6LnE4mTf1NQHnqKGdbA2k0x/08Hh2Gkiwqec/Nzcw7GItakyZKlHaHSce32Eib171LJgvQ2t2w2yMlTUq1pIXA3SpQq4vn7VDy750IBwsUWALpQyuu3NT0R5QcMAzjWAKN4/vJgcs14GJceNk6NYYLQ5TmG/ZeiZCjcXNVXqUGnjCUJwKmuDkISkro7hvxclVBM6Pa7tqvYGrBUX7n1boTlY1Gyn1Mv1UExEFI5Gk4iJcwXSAU7TVbrlnqlkF+cjJRobGaSWctZEQpRfzT197T7AabcdnD+IgrRxgvuKWdYQDcrBQ=
  on:
    tags: true
    branch: master
    repo: bsunderhus/html-module-loader
